/**
 * Constantes globales del dominio. Evita "magic strings" repartidos por el código.
 */
module.exports = {
  GLOBAL_ROLES: {
    SUPER_ADMIN: 'SUPER_ADMIN',
    DEVELOPER: 'DEVELOPER',
    SUPPORT: 'SUPPORT',
  },

  USER_STATUS: {
    ACTIVE: 'active',
    SUSPENDED: 'suspended',
    PENDING: 'pending',
    BLOCKED: 'blocked',
  },

  CLUB_STATUS: {
    ACTIVE: 'active',
    INACTIVE: 'inactive',
    SUSPENDED: 'suspended',
  },

  USER_CLUB_STATUS: {
    ACTIVE: 'active',
    SUSPENDED: 'suspended',
    PENDING: 'pending',
  },

  INVITATION_STATUS: {
    ACTIVE: 'active',
    REVOKED: 'revoked',
    EXPIRED: 'expired',
    EXHAUSTED: 'exhausted',
  },

  JOIN_REQUEST_STATUS: {
    PENDING: 'pending',
    APPROVED: 'approved',
    REJECTED: 'rejected',
  },

  ROLE_SCOPE: {
    GLOBAL: 'global',
    CLUB: 'club',
  },

  NOTIFICATION_TYPE: {
    INFO: 'info',
    SUCCESS: 'success',
    WARNING: 'warning',
    ERROR: 'error',
  },

  TOKEN_TYPE: {
    VERIFY_EMAIL: 'verify_email',
    RESET_PASSWORD: 'reset_password',
  },

  CHARGE_RECURRENCE: {
    ONCE: 'once',
    MONTHLY: 'monthly',
    YEARLY: 'yearly',
  },

  CHARGE_STATUS: {
    ACTIVE: 'active',
    INACTIVE: 'inactive',
  },

  CHARGE_INSTANCE_STATUS: {
    PENDING: 'pending',
    PARTIAL: 'partial',
    PAID: 'paid',
    EXEMPT: 'exempt',
  },

  /** Dos "sabores" de `charge_instances.status = 'exempt'` — ambos bloquean el registro de un
   * pago igual, solo cambian la etiqueta/color mostrados: FROZEN ("congelado", ej. un jugador de
   * licencia) vs NOT_APPLICABLE ("no aplica", ej. el entrenador un mes puntual). Guardado aparte
   * en `exempt_type` en vez de inferirlo del texto libre de `exempt_reason`. */
  CHARGE_EXEMPT_TYPE: {
    FROZEN: 'frozen',
    NOT_APPLICABLE: 'not_applicable',
  },

  FUNCTIONS: {
    // Plataforma / global
    MANAGE_PLATFORM: 'MANAGE_PLATFORM',
    VIEW_ALL_CLUBS: 'VIEW_ALL_CLUBS',
    EDIT_ALL_CLUBS: 'EDIT_ALL_CLUBS',
    VIEW_ALL_FUNCTIONS: 'VIEW_ALL_FUNCTIONS',
    VIEW_PLATFORM_SETTINGS: 'VIEW_PLATFORM_SETTINGS',
    EDIT_PLATFORM_SETTINGS: 'EDIT_PLATFORM_SETTINGS',
    VIEW_ALL_USERS: 'VIEW_ALL_USERS',
    EDIT_ALL_USERS: 'EDIT_ALL_USERS',
    SUSPEND_ALL_USERS: 'SUSPEND_ALL_USERS',

    // Usuarios
    VIEW_USERS: 'VIEW_USERS',
    CREATE_USERS: 'CREATE_USERS',
    EDIT_USERS: 'EDIT_USERS',
    DELETE_USERS: 'DELETE_USERS',
    SUSPEND_USERS: 'SUSPEND_USERS',
    ASSIGN_USER_ROLES: 'ASSIGN_USER_ROLES',

    // Roles
    VIEW_ROLES: 'VIEW_ROLES',
    CREATE_ROLE: 'CREATE_ROLE',
    EDIT_ROLE: 'EDIT_ROLE',
    DELETE_ROLE: 'DELETE_ROLE',

    // Funcionalidades
    VIEW_FUNCTIONS: 'VIEW_FUNCTIONS',

    // Club
    VIEW_CLUB: 'VIEW_CLUB',
    EDIT_CLUB: 'EDIT_CLUB',
    MANAGE_SETTINGS: 'MANAGE_SETTINGS',
    DELETE_CLUB: 'DELETE_CLUB',

    // Invitaciones
    VIEW_INVITATIONS: 'VIEW_INVITATIONS',
    CREATE_INVITATIONS: 'CREATE_INVITATIONS',
    REVOKE_INVITATIONS: 'REVOKE_INVITATIONS',
    MANAGE_JOIN_REQUESTS: 'MANAGE_JOIN_REQUESTS',

    // Dashboard / auditoría
    VIEW_DASHBOARD: 'VIEW_DASHBOARD',
    VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',

    // Notificaciones
    VIEW_NOTIFICATIONS: 'VIEW_NOTIFICATIONS',
    MANAGE_NOTIFICATIONS: 'MANAGE_NOTIFICATIONS',

    // Miembros
    VIEW_MEMBERS_DASHBOARD: 'VIEW_MEMBERS_DASHBOARD',
    VIEW_MEMBERS: 'VIEW_MEMBERS',
    VIEW_MEMBERS_SCOPED: 'VIEW_MEMBERS_SCOPED',
    CREATE_MEMBERS: 'CREATE_MEMBERS',
    EDIT_MEMBERS: 'EDIT_MEMBERS',
    DELETE_MEMBERS: 'DELETE_MEMBERS',
    LINK_MEMBER_USER: 'LINK_MEMBER_USER',
    VIEW_MEMBER_GROUPS: 'VIEW_MEMBER_GROUPS',
    MANAGE_MEMBER_GROUPS: 'MANAGE_MEMBER_GROUPS',
    VIEW_MEMBER_TAGS: 'VIEW_MEMBER_TAGS',
    MANAGE_MEMBER_TAGS: 'MANAGE_MEMBER_TAGS',
    VIEW_MEMBER_FIELDS: 'VIEW_MEMBER_FIELDS',
    CREATE_MEMBER_FIELDS: 'CREATE_MEMBER_FIELDS',
    EDIT_MEMBER_FIELDS: 'EDIT_MEMBER_FIELDS',
    DELETE_MEMBER_FIELDS: 'DELETE_MEMBER_FIELDS',

    // Tesorería
    VIEW_TREASURY_DASHBOARD: 'VIEW_TREASURY_DASHBOARD',
    VIEW_CHARGES: 'VIEW_CHARGES',
    CREATE_CHARGES: 'CREATE_CHARGES',
    EDIT_CHARGES: 'EDIT_CHARGES',
    DELETE_CHARGES: 'DELETE_CHARGES',
    VIEW_PAYMENTS: 'VIEW_PAYMENTS',
    VIEW_PAYMENTS_SCOPED: 'VIEW_PAYMENTS_SCOPED',
    CREATE_PAYMENTS: 'CREATE_PAYMENTS',
    EDIT_PAYMENTS: 'EDIT_PAYMENTS',
    DELETE_PAYMENTS: 'DELETE_PAYMENTS',
    EXEMPT_PAYMENTS: 'EXEMPT_PAYMENTS',
    VIEW_TREASURY_SETTINGS: 'VIEW_TREASURY_SETTINGS',
    EDIT_TREASURY_SETTINGS: 'EDIT_TREASURY_SETTINGS',
    VIEW_EXPENSES: 'VIEW_EXPENSES',
    CREATE_EXPENSES: 'CREATE_EXPENSES',
    EDIT_EXPENSES: 'EDIT_EXPENSES',
    DELETE_EXPENSES: 'DELETE_EXPENSES',
  },

  PAGINATION: {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 20,
    MAX_LIMIT: 100,
  },
};
